// <auto-generated />
using System;
using System.Numerics;
using MDAO_Challenge_Bot.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MDAO_Challenge_Bot.Migrations
{
    [DbContext(typeof(ChallengeDBContext))]
    [Migration("20230425001341_AddAirtableChallenges")]
    partial class AddAirtableChallenges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MDAO_Challenge_Bot.Models.AirtableChallenge", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Batch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BountyProgram")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("AirtableChallenges", (string)null);
                });

            modelBuilder.Entity("MDAO_Challenge_Bot.Models.LaborMarket", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LastUpdatedAtBlockHeight")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LaborMarket", (string)null);
                });

            modelBuilder.Entity("MDAO_Challenge_Bot.Models.LaborMarketRequest", b =>
                {
                    b.Property<long>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("RequestId"));

                    b.Property<decimal>("ClaimSubmitExpiration")
                        .HasColumnType("numeric(20,0)");

                    b.Property<string>("IPFSUri")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LaborMarketId")
                        .HasColumnType("bigint");

                    b.Property<string>("PaymentTokenAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<BigInteger>("PaymentTokenAmount")
                        .HasColumnType("numeric");

                    b.Property<string>("Requester")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("ReviewExpiration")
                        .HasColumnType("numeric(20,0)");

                    b.Property<decimal>("SubmitExpiration")
                        .HasColumnType("numeric(20,0)");

                    b.HasKey("RequestId");

                    b.HasIndex("LaborMarketId");

                    b.ToTable("LaborMarketRequests", (string)null);
                });

            modelBuilder.Entity("MDAO_Challenge_Bot.Models.LaborMarketRequest", b =>
                {
                    b.HasOne("MDAO_Challenge_Bot.Models.LaborMarket", "LaborMarket")
                        .WithMany("Requests")
                        .HasForeignKey("LaborMarketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LaborMarket");
                });

            modelBuilder.Entity("MDAO_Challenge_Bot.Models.LaborMarket", b =>
                {
                    b.Navigation("Requests");
                });
#pragma warning restore 612, 618
        }
    }
}
